# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61030909ae772628fb654567dbba6cac"
name = "discount-app"
handle = "discount-app-840"
application_url = "https://hello-ground-surprise-sperm.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-jorge-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://hello-ground-surprise-sperm.trycloudflare.com/auth/callback",
  "https://hello-ground-surprise-sperm.trycloudflare.com/auth/shopify/callback",
  "https://hello-ground-surprise-sperm.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
